// Generated by delombok at Tue Jun 20 17:11:51 CST 2023
package com.example.delombok.access;

import jakarta.persistence.*;

@Entity
@Table(name = "t_Category")
public class Category {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CategoryID")
    private Integer categoryId;
    @Column(name = "CategoryName", length = 50)
    private String categoryName;


    @java.lang.SuppressWarnings("all")
    public static class CategoryBuilder {
        @java.lang.SuppressWarnings("all")
        private Integer categoryId;
        @java.lang.SuppressWarnings("all")
        private String categoryName;

        @java.lang.SuppressWarnings("all")
        CategoryBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Category.CategoryBuilder categoryId(final Integer categoryId) {
            this.categoryId = categoryId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Category.CategoryBuilder categoryName(final String categoryName) {
            this.categoryName = categoryName;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public Category build() {
            return new Category(this.categoryId, this.categoryName);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Category.CategoryBuilder(categoryId=" + this.categoryId + ", categoryName=" + this.categoryName + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static Category.CategoryBuilder builder() {
        return new Category.CategoryBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public void setCategoryId(final Integer categoryId) {
        this.categoryId = categoryId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCategoryName(final String categoryName) {
        this.categoryName = categoryName;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCategoryId() {
        return this.categoryId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCategoryName() {
        return this.categoryName;
    }

    @java.lang.SuppressWarnings("all")
    public Category(final Integer categoryId, final String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }

    @java.lang.SuppressWarnings("all")
    public Category() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Category(categoryId=" + this.getCategoryId() + ", categoryName=" + this.getCategoryName() + ")";
    }
}
