// Generated by delombok at Tue Jun 20 17:11:51 CST 2023
package com.example.delombok.access;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Gender {
    Unknown(0), Male(1), Female(2);
    final int code;

    @JsonValue
    String toJsonValue() {
        return switch (this) {
            case Unknown -> "未知";
            case Male -> "男";
            case Female -> "女";
        };
    }

    @java.lang.SuppressWarnings("all")
    public int getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    private Gender(final int code) {
        this.code = code;
    }
}
