// Generated by delombok at Tue Jun 20 17:11:51 CST 2023
package com.example.delombok.access;

import jakarta.persistence.*;

import java.math.BigDecimal;

@Entity
@Table(name = "t_OrderDetail")
public class OrderDetail {
    @Id
    @Column(name = "OrderDetailID")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer orderDetailId;
    @ManyToOne
    @JoinColumn(name = "OrderID")
    private Order order;
    @ManyToOne
    @JoinColumn(name = "CommodityID")
    private Commodity commodity;
    @Column(name = "Quantity")
    private Integer quantity;
    @Column(name = "UnitPrice", precision = 10, scale = 2)
    private BigDecimal unitPrice;


    @java.lang.SuppressWarnings("all")
    public static class OrderDetailBuilder {
        @java.lang.SuppressWarnings("all")
        private Integer orderDetailId;
        @java.lang.SuppressWarnings("all")
        private Order order;
        @java.lang.SuppressWarnings("all")
        private Commodity commodity;
        @java.lang.SuppressWarnings("all")
        private Integer quantity;
        @java.lang.SuppressWarnings("all")
        private BigDecimal unitPrice;

        @java.lang.SuppressWarnings("all")
        OrderDetailBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OrderDetail.OrderDetailBuilder orderDetailId(final Integer orderDetailId) {
            this.orderDetailId = orderDetailId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OrderDetail.OrderDetailBuilder order(final Order order) {
            this.order = order;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OrderDetail.OrderDetailBuilder commodity(final Commodity commodity) {
            this.commodity = commodity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OrderDetail.OrderDetailBuilder quantity(final Integer quantity) {
            this.quantity = quantity;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OrderDetail.OrderDetailBuilder unitPrice(final BigDecimal unitPrice) {
            this.unitPrice = unitPrice;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public OrderDetail build() {
            return new OrderDetail(this.orderDetailId, this.order, this.commodity, this.quantity, this.unitPrice);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "OrderDetail.OrderDetailBuilder(orderDetailId=" + this.orderDetailId + ", order=" + this.order + ", commodity=" + this.commodity + ", quantity=" + this.quantity + ", unitPrice=" + this.unitPrice + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static OrderDetail.OrderDetailBuilder builder() {
        return new OrderDetail.OrderDetailBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public void setOrderDetailId(final Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    @java.lang.SuppressWarnings("all")
    public void setOrder(final Order order) {
        this.order = order;
    }

    @java.lang.SuppressWarnings("all")
    public void setCommodity(final Commodity commodity) {
        this.commodity = commodity;
    }

    @java.lang.SuppressWarnings("all")
    public void setQuantity(final Integer quantity) {
        this.quantity = quantity;
    }

    @java.lang.SuppressWarnings("all")
    public void setUnitPrice(final BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getOrderDetailId() {
        return this.orderDetailId;
    }

    @java.lang.SuppressWarnings("all")
    public Order getOrder() {
        return this.order;
    }

    @java.lang.SuppressWarnings("all")
    public Commodity getCommodity() {
        return this.commodity;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getQuantity() {
        return this.quantity;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    @java.lang.SuppressWarnings("all")
    public OrderDetail(final Integer orderDetailId, final Order order, final Commodity commodity, final Integer quantity, final BigDecimal unitPrice) {
        this.orderDetailId = orderDetailId;
        this.order = order;
        this.commodity = commodity;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }

    @java.lang.SuppressWarnings("all")
    public OrderDetail() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "OrderDetail(orderDetailId=" + this.getOrderDetailId() + ", order=" + this.getOrder() + ", commodity=" + this.getCommodity() + ", quantity=" + this.getQuantity() + ", unitPrice=" + this.getUnitPrice() + ")";
    }
}
