// Generated by delombok at Tue Jun 20 17:11:51 CST 2023
package com.example.delombok.access;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "t_Order")
public class Order {
    @Id
    @Column(name = "OrderID")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer orderId;
    @ManyToOne
    @JoinColumn(name = "Username")
    private User user;
    @Column(name = "OrderDate", columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    private Date orderDate;
    @Column(name = "OrderStatus", length = 50)
    private String orderStatus;
    @Column(name = "TotalAmount", precision = 10, scale = 2)
    private BigDecimal totalAmount;


    @java.lang.SuppressWarnings("all")
    public static class OrderBuilder {
        @java.lang.SuppressWarnings("all")
        private Integer orderId;
        @java.lang.SuppressWarnings("all")
        private User user;
        @java.lang.SuppressWarnings("all")
        private Date orderDate;
        @java.lang.SuppressWarnings("all")
        private String orderStatus;
        @java.lang.SuppressWarnings("all")
        private BigDecimal totalAmount;

        @java.lang.SuppressWarnings("all")
        OrderBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Order.OrderBuilder orderId(final Integer orderId) {
            this.orderId = orderId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Order.OrderBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Order.OrderBuilder orderDate(final Date orderDate) {
            this.orderDate = orderDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Order.OrderBuilder orderStatus(final String orderStatus) {
            this.orderStatus = orderStatus;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Order.OrderBuilder totalAmount(final BigDecimal totalAmount) {
            this.totalAmount = totalAmount;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public Order build() {
            return new Order(this.orderId, this.user, this.orderDate, this.orderStatus, this.totalAmount);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Order.OrderBuilder(orderId=" + this.orderId + ", user=" + this.user + ", orderDate=" + this.orderDate + ", orderStatus=" + this.orderStatus + ", totalAmount=" + this.totalAmount + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static Order.OrderBuilder builder() {
        return new Order.OrderBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public void setOrderId(final Integer orderId) {
        this.orderId = orderId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    public void setOrderDate(final Date orderDate) {
        this.orderDate = orderDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setOrderStatus(final String orderStatus) {
        this.orderStatus = orderStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalAmount(final BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getOrderId() {
        return this.orderId;
    }

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public Date getOrderDate() {
        return this.orderDate;
    }

    @java.lang.SuppressWarnings("all")
    public String getOrderStatus() {
        return this.orderStatus;
    }

    @java.lang.SuppressWarnings("all")
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }

    @java.lang.SuppressWarnings("all")
    public Order(final Integer orderId, final User user, final Date orderDate, final String orderStatus, final BigDecimal totalAmount) {
        this.orderId = orderId;
        this.user = user;
        this.orderDate = orderDate;
        this.orderStatus = orderStatus;
        this.totalAmount = totalAmount;
    }

    @java.lang.SuppressWarnings("all")
    public Order() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Order(orderId=" + this.getOrderId() + ", user=" + this.getUser() + ", orderDate=" + this.getOrderDate() + ", orderStatus=" + this.getOrderStatus() + ", totalAmount=" + this.getTotalAmount() + ")";
    }
}
