// Generated by delombok at Tue Jun 20 17:11:51 CST 2023
package com.example.delombok.domain;

import java.util.ArrayList;
import java.util.List;

public class TResult<T> {
    private boolean success;
    private String message;
    private T data;
    public final List<Object> errors = new ArrayList<>();

    public static <U> TResult<U> success() {
        return TResult.<U>builder().success(true).build();
    }

    public static <U> TResult<U> success(U data) {
        return TResult.<U>builder().success(true).data(data).build();
    }

    public static <U> TResult<U> error(String message) {
        return TResult.<U>builder().success(false).message(message).build();
    }

    public TResult<T> addErrors(Object error) {
        errors.add(error);
        return this;
    }


    @java.lang.SuppressWarnings("all")
    public static class TResultBuilder<T> {
        @java.lang.SuppressWarnings("all")
        private boolean success;
        @java.lang.SuppressWarnings("all")
        private String message;
        @java.lang.SuppressWarnings("all")
        private T data;

        @java.lang.SuppressWarnings("all")
        TResultBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TResult.TResultBuilder<T> success(final boolean success) {
            this.success = success;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TResult.TResultBuilder<T> message(final String message) {
            this.message = message;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public TResult.TResultBuilder<T> data(final T data) {
            this.data = data;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public TResult<T> build() {
            return new TResult<T>(this.success, this.message, this.data);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "TResult.TResultBuilder(success=" + this.success + ", message=" + this.message + ", data=" + this.data + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static <T> TResult.TResultBuilder<T> builder() {
        return new TResult.TResultBuilder<T>();
    }

    @java.lang.SuppressWarnings("all")
    public void setSuccess(final boolean success) {
        this.success = success;
    }

    @java.lang.SuppressWarnings("all")
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    public void setData(final T data) {
        this.data = data;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isSuccess() {
        return this.success;
    }

    @java.lang.SuppressWarnings("all")
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    public T getData() {
        return this.data;
    }

    @java.lang.SuppressWarnings("all")
    public List<Object> getErrors() {
        return this.errors;
    }

    @java.lang.SuppressWarnings("all")
    public TResult(final boolean success, final String message, final T data) {
        this.success = success;
        this.message = message;
        this.data = data;
    }

    @java.lang.SuppressWarnings("all")
    public TResult() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "TResult(success=" + this.isSuccess() + ", message=" + this.getMessage() + ", data=" + this.getData() + ", errors=" + this.getErrors() + ")";
    }
}
