// Generated by delombok at Tue Jun 20 17:11:51 CST 2023
package com.example.delombok.controller.dev;

import com.example.delombok.access.Category;
import com.example.delombok.domain.Result;
import com.example.delombok.repository.CategoryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/dev/category")
public class DevCategoryController {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(DevCategoryController.class);
    @Autowired
    private CategoryRepository categoryRepository;

    //查询所有商品种类
    @GetMapping("/all")
    public Result findAll() {
        return Result.success(categoryRepository.findAll());
    }

    //更新种类信息
    @PutMapping
    public Result updateCategory(@RequestBody Category category) {
        try {
            categoryRepository.save(category);
            return Result.success();
        } catch (Exception e) {
            return Result.error(e.getMessage()).addErrors(e);
        }
    }

    //如果该商品种类下的商品不为null，则无法删除
    @DeleteMapping
    public Result deleteCategoryById(@RequestParam Integer categoryId) {
        try {
            categoryRepository.deleteById(categoryId);
            return Result.success();
        } catch (Exception e) {
            return Result.error(e.getMessage()).addErrors(e);
        }
    }

    //增加商品品种类信息
    @PostMapping
    public Result addCategory(@RequestBody Category category) {
        try {
            categoryRepository.save(category);
            return Result.success();
        } catch (Exception e) {
            return Result.error(e.getMessage()).addErrors(e);
        }
    }
}
