// Generated by delombok at Tue Jun 20 17:11:51 CST 2023
package com.example.delombok.domain.req.auth;

import lombok.*;

public class LoginRequestBody {
    @NonNull
    private String username;
    @NonNull
    private String password;


    @java.lang.SuppressWarnings("all")
    public static class LoginRequestBodyBuilder {
        @java.lang.SuppressWarnings("all")
        private String username;
        @java.lang.SuppressWarnings("all")
        private String password;

        @java.lang.SuppressWarnings("all")
        LoginRequestBodyBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public LoginRequestBody.LoginRequestBodyBuilder username(@NonNull final String username) {
            if (username == null) {
                throw new java.lang.NullPointerException("username is marked non-null but is null");
            }
            this.username = username;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public LoginRequestBody.LoginRequestBodyBuilder password(@NonNull final String password) {
            if (password == null) {
                throw new java.lang.NullPointerException("password is marked non-null but is null");
            }
            this.password = password;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public LoginRequestBody build() {
            return new LoginRequestBody(this.username, this.password);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "LoginRequestBody.LoginRequestBodyBuilder(username=" + this.username + ", password=" + this.password + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static LoginRequestBody.LoginRequestBodyBuilder builder() {
        return new LoginRequestBody.LoginRequestBodyBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public void setUsername(@NonNull final String username) {
        if (username == null) {
            throw new java.lang.NullPointerException("username is marked non-null but is null");
        }
        this.username = username;
    }

    @java.lang.SuppressWarnings("all")
    public void setPassword(@NonNull final String password) {
        if (password == null) {
            throw new java.lang.NullPointerException("password is marked non-null but is null");
        }
        this.password = password;
    }

    @NonNull
    @java.lang.SuppressWarnings("all")
    public String getUsername() {
        return this.username;
    }

    @NonNull
    @java.lang.SuppressWarnings("all")
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    public LoginRequestBody(@NonNull final String username, @NonNull final String password) {
        if (username == null) {
            throw new java.lang.NullPointerException("username is marked non-null but is null");
        }
        if (password == null) {
            throw new java.lang.NullPointerException("password is marked non-null but is null");
        }
        this.username = username;
        this.password = password;
    }

    @java.lang.SuppressWarnings("all")
    public LoginRequestBody() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "LoginRequestBody(username=" + this.getUsername() + ", password=" + this.getPassword() + ")";
    }
}
