// Generated by delombok at Tue Jun 20 17:11:51 CST 2023
package com.example.delombok.domain.res.auth;

public class LoginResponseData {
    String accessToken;
    String refreshToken;


    @java.lang.SuppressWarnings("all")
    public static class LoginResponseDataBuilder {
        @java.lang.SuppressWarnings("all")
        private String accessToken;
        @java.lang.SuppressWarnings("all")
        private String refreshToken;

        @java.lang.SuppressWarnings("all")
        LoginResponseDataBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public LoginResponseData.LoginResponseDataBuilder accessToken(final String accessToken) {
            this.accessToken = accessToken;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public LoginResponseData.LoginResponseDataBuilder refreshToken(final String refreshToken) {
            this.refreshToken = refreshToken;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public LoginResponseData build() {
            return new LoginResponseData(this.accessToken, this.refreshToken);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "LoginResponseData.LoginResponseDataBuilder(accessToken=" + this.accessToken + ", refreshToken=" + this.refreshToken + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static LoginResponseData.LoginResponseDataBuilder builder() {
        return new LoginResponseData.LoginResponseDataBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public void setAccessToken(final String accessToken) {
        this.accessToken = accessToken;
    }

    @java.lang.SuppressWarnings("all")
    public void setRefreshToken(final String refreshToken) {
        this.refreshToken = refreshToken;
    }

    @java.lang.SuppressWarnings("all")
    public String getAccessToken() {
        return this.accessToken;
    }

    @java.lang.SuppressWarnings("all")
    public String getRefreshToken() {
        return this.refreshToken;
    }

    @java.lang.SuppressWarnings("all")
    public LoginResponseData(final String accessToken, final String refreshToken) {
        this.accessToken = accessToken;
        this.refreshToken = refreshToken;
    }

    @java.lang.SuppressWarnings("all")
    public LoginResponseData() {
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "LoginResponseData(accessToken=" + this.getAccessToken() + ", refreshToken=" + this.getRefreshToken() + ")";
    }
}
