// Generated by delombok at Tue Jun 20 17:11:51 CST 2023
package com.example.delombok.initializer;

import org.jetbrains.annotations.NotNull;
import org.springframework.boot.context.event.ApplicationStartedEvent;
import org.springframework.context.ApplicationListener;
import org.springframework.stereotype.Component;

@Component
public class SpringBootStartListener implements ApplicationListener<ApplicationStartedEvent> {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(SpringBootStartListener.class);

    @Override
    public void onApplicationEvent(@NotNull ApplicationStartedEvent event) {
        log.info(getClass().getName());
    }
}
