// Generated by delombok at Tue Jun 20 17:11:51 CST 2023
package com.example.delombok.initializer;

import jakarta.annotation.PostConstruct;
import org.springframework.stereotype.Component;

@Component
public class SpringStartInit {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(SpringStartInit.class);

    @PostConstruct
    public void init() throws Exception {
        log.info(getClass().getName());
    }
}
